[package]
name = "my_json"
version = "0.1.0"
authors = ["zekin <wzekin@gmailc.om>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
